controller:
  minAvailable: 1
  replicaCount: 1
  resources:
    requests:
      cpu: 500m
      memory: 500Mi
  autoscaling:
    enabled: true
    minReplicas: 1
    maxReplicas: 2
  affinity: {}
  config:
    ### BROTLI ###
    enable-brotli: "true"                 # type: bool, default: false
    brotli-level: 5                       # type: int, default: 4
    brotli-min-length: 20                 # type: int, default: 20

    ### GZIP ###
    use-gzip: "true"                     # type: bool, default: false
    gzip-level: 5                         # type: int, default: 1
    gzip-min-length: 256                  # type: int, default: 256
